// <auto-generated />
using System;
using CatalogService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424220733_AddLuotBanToSanPham")]
    partial class AddLuotBanToSanPham
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatalogService.Models.ChiTietSanPham", b =>
                {
                    b.Property<Guid>("MaCTSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Anh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KichCo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MaSP")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaCTSP");

                    b.HasIndex("MaSP");

                    b.ToTable("ChiTietSanPhams");
                });

            modelBuilder.Entity("CatalogService.Models.DanhMuc", b =>
                {
                    b.Property<Guid>("MaDM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaLDM")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenDM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDM");

                    b.HasIndex("MaLDM");

                    b.ToTable("DanhMucs");
                });

            modelBuilder.Entity("CatalogService.Models.LoaiDanhMuc", b =>
                {
                    b.Property<Guid>("MaLDM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenLDM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLDM");

                    b.ToTable("LoaiDanhMucs");
                });

            modelBuilder.Entity("CatalogService.Models.SanPham", b =>
                {
                    b.Property<Guid>("MaSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LuotBan")
                        .HasColumnType("int");

                    b.Property<Guid>("MaDM")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaSP");

                    b.HasIndex("MaDM");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("CatalogService.Models.ChiTietSanPham", b =>
                {
                    b.HasOne("CatalogService.Models.SanPham", "SanPham")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("CatalogService.Models.DanhMuc", b =>
                {
                    b.HasOne("CatalogService.Models.LoaiDanhMuc", "LoaiDanhMuc")
                        .WithMany("DanhMucs")
                        .HasForeignKey("MaLDM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiDanhMuc");
                });

            modelBuilder.Entity("CatalogService.Models.SanPham", b =>
                {
                    b.HasOne("CatalogService.Models.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaDM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("CatalogService.Models.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("CatalogService.Models.LoaiDanhMuc", b =>
                {
                    b.Navigation("DanhMucs");
                });

            modelBuilder.Entity("CatalogService.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
